### PR TITLE
es-ES translated.

### PR DESCRIPTION
**Pull request by Wirlie**
I have translated the Spanish language but, I'm not sure if the special characters should be replaced with a special code. What codes can I use for this? 
For example: `ñ = ???` or `á = ???` (I see that the character ' is replaced with `&apos;`)

And, my another problem is that I tried to use QT, but in my window 10, QT does not seem to work... (no errors are displayed, QT never starts).

### CODE REVIEW

**Comment by Wirlie** [comment]
Another question, I do not understand what means this translation: (Line 83)
https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2L83

**Comment by LRFLEW** [comment]
The characters like `ñ` should be fine. From my testing, it does handle Unicode characters like that correctly. If there is an `&` code for it, I'll deal with it once it's merged.

The line "Window edge snapping distance:" is a bit weird. Essentially, if you move any of the in-game windows around (example, a ride window), it will try to align the edge of the window to the edge of the screen if the window is close to it. So if you move a window over to the left side of the screen, it will line up exactly with the screen once you get close enough. This option adjusts the distance the window has to be from the edge for the snapping to occur.

The only note I have right now with it is that any strings that aren't changed (such as line 51) should be left empty. If there's no text in the translation, it will default to the original string anyways.

**Comment by Wirlie** [comment]
Thanks for your review and thanks for your answer, ~~I already have changed the line 45 and 51~~ I left empty translations of lines [R51](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R51) and [R193](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R193) because I prefer to use the English translation instead of the Spanish translation because these two strings are not translatable for me (for example, 'commit' is used in Spanish without a translation because it is a foreign/technical word, I don't know if I explained this properly, the same goes for ~~'build'~~, 'hash', etc.).

My only question now is if is it necessary to add the `type="unfinished"` property? (at [this line](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R51) and [this line](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R193) into the `<translation>` tag.).

**Comment by LRFLEW** [comment]
You should leave the  `type="unfinished"` off of any lines you are vouching for, even if you are leaving it blank. You have done it correctly from what I've seen.

I was looking over it before merging it when I noticed something. The translation on [R96](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R96) ("Permitir carga de archivos con una suma de comprobación incorrect") is a little too long for the window. Currently, the last word is slightly clipped off, making it look bad. There are two options. I can make the window larger (for everybody, not just the Spanish translation), which would easily fit it. However, since this string came from the original game, I can also just replace it with the version from the game ("Permitir cargar ficheros dañados"), which does fit. From the Spanish I know, it appears that the game's translation isn't completely accurate, which would make yours a bit better. However, it may also make sense to try to keep the same option translated the same way. I'm not sure what the best option is. What do you think?

**Comment by Wirlie** [comment]
You're right, I prefer to use "Permitir cargar ficheros dañados" because it is a short translation and it means the same as the another string that I had translated before. Thanks! I hadn't seen that the original game already had this translation. I have already implemented the necessary changes, I think.

**Comment by LRFLEW** [comment]
You don't need to mark the translations as "unfinished" if you don't think it _can_ be directly translated. If you're expecting someone (you or someone else) to change it, then keep the "unfinished" attribute. Otherwise, go ahead and remove it. I will go ahead and merge this in a little bit.

**Comment by Wirlie** [comment]
Oh okay, I had not understood and I thought it was necessary. I have already removed the "unfinished" label. :) Thanks!

**Comment by Wirlie** [comment]
I think that this is ready for merge. (?)

**Comment by LRFLEW** [comment]
I'll take a minute to review it now. The only comment I have right now is that some of the comments ([R49](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R49) and [R191](https://github.com/LRFLEW/OpenRCT2Launcher/pull/7/files#diff-517d1e3fe6a157b514de8521dda64cc2R191)) don't make any sense now that you removed the "unfinished" tag :P

**Comment by LRFLEW** [comment]
I looked over it. The only other issues I see are some punctuation/formatting issues, which I can fix myself. I also need to make more punctuation changes myself, so it's not an issue for me to do it.

**Comment by Wirlie** [comment]
Oh I'm sorry, I forgot to remove comments. (I added these comments to explain the reason of the "unfinished" label.) Done :p 

and your another comment... I cannot see where I'm wrong. I hope that you can fix it xP

**Comment by LRFLEW** [comment]
Thank you so much for contributing :D

**Comment by Wirlie** [comment]
No problem, and sorry for my bad english :P (I can read and understand English but I can't write in English correctly :x)

Thank you very much for your time ^-^

**Pull request merged**
