### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by LRFLEW** [comment]
I see some issues:
- The translation of "Hide RCT1 Mega Park when not unlocked" as "Verberg het RCT1 Mega Park wanneer deze nog niet ontgrendeld is" is clipping for me (it drops the last word)
- The translation of "Max number of player on server:" as "Maximum aantal spelers op de server:" is clipping for me (some of the first 'M' is cut off)
- "Start OpenRCT2" seems long to me. Could it just be "Start"?

For the clipping, I'm still deciding how it should be handled (see #7 )

**Comment by LRFLEW** [comment]
Ok, I fixed the overflow thing from the window size. It was caused by a decision I made a few versions ago due to how many tabs I had. Now that I've simplified the window, I made it resizable, which allows Qt to change the size to fit the content. I'd still like you to consider making some of the longer strings shorter if possible, but it's not a huge issue.

Though the "Start OpenRCT2" button being long is still an issue, as that window can't be resizable right now due to a bug in Qt, and the larger that button is, the less room there is to display error messages. If you can shorten/simplify that, it would help a lot.

**Comment by Broxzier** [comment]
I've shortened some of the translated strings now. "Start OpenRCT2" is now just "Starten", which is less of an imperative. I can't test the clipping myself as everything looks good on my end.

**Comment by LRFLEW** [comment]
Al I'm waiting on for this is a shorter translation for "bin dir not created". I don't care if it's very good or not (you can always PR a change later), but I would like it at least usable before I merge it.

**Comment by Broxzier** [comment]
Okay, I will make the change Gymnasiast proposed.

**Comment by Broxzier** [comment]
Changed
`De bin map kon niet worden aangemaakt`
to
`Fout bij maken van 'bin'-map`

Will this fit?

**Comment by LRFLEW** [comment]
It's close enough that there might be a problem on some OS, but I'll take it for now.

**Pull request merged**
