### PR TITLE
sv-SE laucnher translation

### PR DESCRIPTION
**Pull request by Nubbie**
Hey
Have now translated the Swedish version for the translator :)

There might be some changes that needs to be done later on like always in all languages, will also maintain this language 

**PS!
There is a `&apos;` in the text instead of ' - this is just to test to see what happens**

### CODE REVIEW

**Comment by LRFLEW** [comment]
Ok, a few comments/questions:
- I may not know Swedish, but it seems to me that you used "Version" and "Versionen" interchangeably. Is there a reason for when you use one or the other? If not, it might look better if you made it more consistent.
- Is there any way to make the "versionen" implied in "Stabila versionen" and "Utvecklande versionen"? The strings are a little long to comfortably fit without a major change to how I layout the text.
- It appears to handle `'` and `&apos;` the same. I'd prefer to keep the repository consistent, and since Qt-Linguist prefers `&apos;`, I'd like it if you switched that back.
- There are a few strings where you removed a trailing space. That space is needed to keep the spacing consistent. Can you please add in the trailing whitespace where the original string had it?
- If something translates without any changes, leave the translation blank. As long as it's marked as translated, it will work correctly, and it saves (some) space in the app.
- I realized some strings really shouldn't be translatable (specifically "Player" and "Server" as they're value defaults). I'm going to go ahead and remove those strings from the translation files to keep the repository cleaner and make it easier for other translators. This may mean that this PR will need a rebase, as you did provide translations for those strings.

Otherwise, this looks really good. Thank you.

**Comment by Nubbie** [comment]
**Have re-based the file now and corrected the mistakes :)**

> I may not know Swedish, but it seems to me that you used "Version" and "Versionen" interchangeably.

**'Version'** and **'Versionen'** has to do with the 'common gender' as it seems to be called in English, 'Version' can be whatever version, 'Versionen' means a specific object/version
Have no clue if that made sense for you, but on the  [Swedish wiktionary](https://sv.wiktionary.org/wiki/version) can you see they use two examples for the word :p 
I have tried to rephrase them a bit now

> Is there any way to make the "versionen" implied in "Stabila versionen" and "Utvecklande versionen"?

FIxed!

> It appears to handle ' and `&apos;` the same.

:+1: Will only use `&apos;` like Qt gives me then

> There are a few strings where you removed a trailing space. + if something translates without any changes

Fixed! (removed my comments too, saves space and wasnt needed)

**Comment by Nubbie** [comment]
This branch has conflicts that must be resolved
Strange...

**Comment by LRFLEW** [comment]
I've manually rebased and merged this PR because of the conflicts. This should be "Merged", so I'm going to close it now.

**Pull request closed without merging**
